### ISSUE TITLE
you can't even see the play button on most screen resolutions.

### ISSUE THREAD

**Issue by sidney-pham** [lecafard/sdd-game#1]
lol

**Comment by lecafard** [comment]
Nah it's just ur screen

**Comment by sidney-pham** [comment]
ram had the same problem

**Comment by sidney-pham** [comment]
and why do u reply quicker here than on fb

**Comment by lecafard** [comment]
Well something's off, btw this is not a chat platform so don't use it as one.

**Comment by sidney-pham** [comment]
sorry mr nazi man
